// Code generated by "stringer -type AuxFakeCoin -linecomment"; DO NOT EDIT.

package aptos

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuxFakeCoin_USDC-0]
	_ = x[AuxFakeCoin_ETH-1]
	_ = x[AuxFakeCoin_BTC-2]
	_ = x[AuxFakeCoin_SOL-3]
	_ = x[AuxFakeCoin_AUX-4]
	_ = x[AuxFakeCoin_USDT-5]
}

const _AuxFakeCoin_name = "USDCETHBTCSOLAUXUSDT"

var _AuxFakeCoin_index = [...]uint8{0, 4, 7, 10, 13, 16, 20}

func (i AuxFakeCoin) String() string {
	if i < 0 || i >= AuxFakeCoin(len(_AuxFakeCoin_index)-1) {
		return "AuxFakeCoin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuxFakeCoin_name[_AuxFakeCoin_index[i]:_AuxFakeCoin_index[i+1]]
}
